---
title: "Plant Guide"
output: 
  html_document: 
    theme: yeti
---
<div style="text-align:center;"><h1><b> Phenotype Data</b></h1>  
The following guide explains how to operate within the Phenotype Data module of EcoPLOT. Here we explain the capabilities unique to this module.</div>  
  
  <h2><b>What is Phenotype Data?</b></h2>  
  
  Phenotypic data are qualitative measurements associated with a plant's physical appearance taken across its lifecycle. Some examples are for plant data are height, count of leaves, color, and number of roots. 

<h2><b>Phenotypic Data in EcoPLOT</b></h2>  
  
  The phenotype data module is best utlized when combined with environmental data. If data has already been uploaded to the Environmental module and if that data shares the same sample IDs as those withing your phenotype file, the two will be merged, allowing you to access all experimental variables when creating graphs or performing statistics. The user will be notified if or when the two files are merged successfully. 