---
title: "citations"
author: "Christopher Derek Sanchez"
date: "9/13/2021"
output: html_document
---

<div style="text-align:center">
<h3><b>Citations</b></h3><br></br>
EcoPLOT is constructed from a novel combination of existing R packages. The EcoPLOT development team would like to recognize the following packages for their contributions.  <br></br>
</div>

  Dean Attali (2020). shinyjs: Easily Improve the User Experience of Your Shiny Apps
  in Seconds. R package version 2.0.0. https://CRAN.R-project.org/package=shinyjs
  
  Emmanuel-Lin Toulemonde (2020). dataPreparation: Automated Data Preparation. R
  package version 1.0.1. https://CRAN.R-project.org/package=dataPreparation
  
  Erich Neuwirth (2014). RColorBrewer: ColorBrewer Palettes. R package version
  1.1-2. https://CRAN.R-project.org/package=RColorBrewer
  
  Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy with
  lubridate. Journal of Statistical Software, 40(3), 1-25. URL
  https://www.jstatsoft.org/v40/i03/.
  
  Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping
  and visualizing associated data on phylogeny using ggtree. Molecular Biology and
  Evolution 2018, 35(2):3041-3043. doi: 10.1093/molbev/msy194
  
  Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2021). dplyr: A
  Grammar of Data Manipulation. R package version 1.0.7.
  https://CRAN.R-project.org/package=dplyr
  
  H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York,
  2016.
  
  Hadley Wickham and Jennifer Bryan (2019). readxl: Read Excel Files. R package
  version 1.3.1. https://CRAN.R-project.org/package=readxl
  
  Hadley Wickham (2007). Reshaping Data with the reshape Package. Journal of
  Statistical Software, 21(12), 1-20. URL http://www.jstatsoft.org/v21/i12/.
  
  Hadley Wickham (2019). stringr: Simple, Consistent Wrappers for Common String
  Operations. R package version 1.4.0. https://CRAN.R-project.org/package=stringr
  
  Hadley Wickham (2021). tidyr: Tidy Messy Data. R package version 1.1.3.
  https://CRAN.R-project.org/package=tidyr
  
  Jari Oksanen, F. Guillaume Blanchet, Michael Friendly, Roeland Kindt, Pierre
  Legendre, Dan McGlinn, Peter R. Minchin, R. B. O'Hara, Gavin L. Simpson, Peter
  Solymos, M. Henry H. Stevens, Eduard Szoecs and Helene Wagner (2020). vegan:
  Community Ecology Package. R package version 2.5-7.
  https://CRAN.R-project.org/package=vegan
  
  Joe Cheng, Carson Sievert, Barret Schloerke, Winston Chang, Yihui Xie and Jeff
  Allen (2021). htmltools: Tools for HTML. R package version 0.5.2.
  https://CRAN.R-project.org/package=htmltools
  
  LG Wang, TTY Lam, S Xu, Z Dai, L Zhou, T Feng, P Guo, CW Dunn, BR Jones, T
  Bradley, H Zhu, Y Guan, Y Jiang, G Yu. treeio: an R package for phylogenetic tree
  input and output with richly annotated and associated data. Molecular Biology and
  Evolution 2020, 37(2):599-603. doi: 10.1093/molbev/msz240
  
  Love, M.I., Huber, W., Anders, S. Moderated estimation of fold change and
  dispersion for RNA-seq data with DESeq2 Genome Biology 15(12):550 (2014)
  
  Microsoft Corporation and Steve Weston (2020). doParallel: Foreach Parallel
  Adaptor for the 'parallel' Package. R package version 1.0.16.
  https://CRAN.R-project.org/package=doParallel
  
  Orchestrating high-throughput genomic analysis with Bioconductor. W. Huber, V.J.
  Carey, R. Gentleman, ..., M. Morgan Nature Methods, 2015:12, 115.
  
  phyloseq: An R package for reproducible interactive analysis and graphics of
  microbiome census data. Paul J. McMurdie and Susan Holmes (2013) PLoS ONE
  8(4):e61217.
  
  qiime2R: Importing QIIME2 artifacts and associated data into R sessions. Jordan E
  Bisanz (2018) https://github.com/jbisanz/qiime2R.
  
  Sumanta Basu and Karl Kumbier (2018). iRF: Iterative Random Forests. R package
  version 3.0.0.
  
  Winston Chang (2021). shinythemes: Themes for Shiny. R package version 1.2.0.
  https://CRAN.R-project.org/package=shinythemes
  
  Winston Chang, Joe Cheng, JJ Allaire, Carson Sievert, Barret Schloerke, Yihui Xie,
  Jeff Allen, Jonathan McPherson, Alan Dipert and Barbara Borges (2021). shiny: Web
  Application Framework for R. R package version 1.6.0.
  https://CRAN.R-project.org/package=shiny
  

  Yihui Xie, Joe Cheng and Xianying Tan (2021). DT: A Wrapper of the JavaScript
  Library 'DataTables'. R package version 0.18.
  https://CRAN.R-project.org/package=DT



