---
title: "Statistics Guide"
output: 
  html_document: 
    theme: yeti
---
<div style="text-align:center"><h1><b> EcoPLOT Statistics Guide  </b></h1>
This guide is meant to assist users in determining which statistical methods they should apply to their dataset.  </div>

<h2><b> Parametric vs. Non-Parametric Tests</h2></b>
Parametric and Non-Parametric tests are statistical methods used to observe significance within a dataset containing a continuous outcome. They differ in the assumptions they make about the underlying statistical distributions present in the data; Parametric tests assume a normal distribution, while Non-Parametric tests do not rely on any.  
  
Descriptions of each are provided below. 

<hr>

<h2><b> Parametric Tests   </h2></b>
  
Parametric tests include t-tests and ANOVA. These tests use the mean to determine significance.  
  
To perform a Parametric test, your data must meet the following requirements:  
1. Data must be **normally distributed**  
2. Data must have been **randomly sampled** from a population  
  
**NOTE:** The assumptions of normality can be ignored if the sample size being tested is large enough  
  
<h4><b><u> T-Test </h4></b></u>
<p style="margin-left:20px;"><b>One Sample T-Test:</b> Used to compare a continuous sample variable mean to a hypothesized mean.  </p>
  
<p style="margin-left:20px;"><b>Two Sample T-Test:</b> Used to compare sample means from **two** groups to test if they are equal or not. The two sample groups must be **independent**  </p>
  
<p style="margin-left:20px;"><b>Paired T-Test:</b> Similar to the two sample t-test but for non-independent sample groups. To perform a Paired T-Test you must ensure that both groups have the same number of samples.  </p>
  
<h4><b><u> ANOVA </h4></b></u>
An ANOVA test expands on the t-test and can be used on samples with 3 or more groupings. ANOVA tests to see if there is an association between the grouping variable and the response variable.  
<p style="margin-left:20px;"><b>One Way ANOVA:</b> Considers one independent variable/factor.  </p>
  
<p style="margin-left:20px;"><b>Two Way ANOVA:</b> Considers two categorical groups.  </p>
  
<h4><b><u> Tukey Honestly Significant Differences (Tukey HSD)  </h4></b></u>
Following a significant ANOVA result, the Tukey HSD test can be used to observe pairwise comparisons between sample groups. This is an effective way of observing which group means within your data are significantly different.  
  
  <hr>
  
<h2><b> Non-Parametric Tests</h2></b>
  
As mentioned before, Non-Parametric tests do not rely on an underlying distribution in your data, meaning your data does not have to exhibit a normal distribution. Non-Parametric tests utilize the median rather than the mean and therefore can be used when the assumptions of parametric tests are not met. Non-Parametric tests are considered to have less power than Parametric tests and should not be used if the requirements for Parametric testing are met.  
  
<h4><b><u> Wilcoxon Rank-Sum (Mann-Whitney U) Test  </h4></b></u>
  
<p style="margin-left:20px;"><b>One-Sample Wilcoxon:</b> This test is used to observe whether or not the sample median is equal to a known/hypothesized median. It is the Non-Parametric equivalent to the One Sample t-test.  </p>
  
<p style="margin-left:20px;"><b>Two-Sample Wilcoxon:</b> Used to compare the medians of two independent groups of samples. It is the Non-Parametric equivalent to the unpaired Two Sample t-test.</p>  
  
<p style="margin-left:20px;"><b>Wilcoxon Sign Rank:</b> Used to compare the medians of two paired sample groups. It is the Non-Parametric equivalent to the Paired t-test.  </p>
  
<h4><b><u> Kruskal Wallis  </h4></b></u>
  
This is the Non-Parametric equivalent to ANOVA. It is used to test if the medians of three of more sample groups are the same. 
  
  <hr>
  
<h2><b> Citations  </h2></b>
  
Baldi, B., and Moore, D.S. (2014). The practice of statistics in the life sciences (W.H Freeman and Company).


